### ISSUE TITLE
EPIC - Design Concepts

### ISSUE THREAD

**Issue by DenisCarriere** [pinax-network/subtivity-substreams#2]
UX Design for the following requirements

## Involved Parties

- UI/UX @DominicF96 
- UI Data requirements: @DenisCarriere @YaroShkvorets 
- Project Owner @chillsauce 

## Requirements

- [x] Current Stats
  - [x] Current TPS
  - [x] Max TPS
  - [x] Block Number
- [x] Historical activity (Transactions)
  - [x] 7 day
  - [x] 30 day
  - [x] 90 day
  - [x] 1 year
  - [x] All-time
- [ ] EVM Chains Supported
  - [x] ETH
  - [x] Polygon
  - [x] BNB Smart Chain
  - [ ] Antelope (Later)
  - [ ] **...others**
- [ ] Search by:
  - [x] Chain
  - [x] Smart Contract Address

## Substream Data requirements

- [ ] Transactions
  - [ ] Unique Transaction ID's
  - [ ] Actions (Events)
- [ ] UAW (Unique Active Wallets) daily aggregate

## Chart comparison
- By Chain Selection (ex: ETH vs. Polygon)
- By Contract (ex: Uniswap vs. PancakeSwap)

The contract schema would be something like:

- `eth:0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984`
- `bsc:0x0e09fabb73bd3ade0a17ecc321fd13a19e81ce82`

## Design examples

https://dappradar.com/eos/other/pomelo

<img width="849" alt="image" src="https://user-images.githubusercontent.com/550895/211709317-2ca781cd-1a1d-40dc-81a7-983fa0e2118f.png">

<img width="842" alt="image" src="https://user-images.githubusercontent.com/550895/211709124-2302e0f3-db4b-4030-b296-36eb0ed4c05b.png">

https://etherscan.io/

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/550895/211709228-71eb6ed3-2979-466b-8af9-bd60b500d124.png">

<img width="1044" alt="image" src="https://user-images.githubusercontent.com/550895/212393048-4b6f866d-756e-469e-a263-ddabee0adc96.png">

**Comment by DominicF96** [comment]
>  - [ ] Search by:
>     - [x] Chain
>     - [ ] Smart Contract Address

@DenisCarriere Will we be implementing Seach by Smart Contract Address in the first release ?

**Comment by DominicF96** [comment]
@DenisCarriere Please review the Figma designs, I think everything's done.
https://www.figma.com/file/iAMvrKMzu7YpNzEyvbNV7m/Subtivity-Web-Platform?node-id=954-2133
