### ISSUE TITLE
EPIC - Infrastructure

### ISSUE THREAD

**Issue by fschoell** [pinax-network/subtivity-substreams#3]
### Services

- PostgreSQL
- Hasura
- Substream to Postgres sink

### Relevant decisions

- PostgreSQL cluster vs multiple concurrent instances (we only have read access to the data, so instead of a PostgreSQL cluster we could just setup 3 sinks that write concurrently into 3 different PostgreSQL instances serving Hasura)?

### Tasks

- [ ] PostgreSQL deployment
- [ ] Hasura deployment
- [ ] PostgreSQL sink deployment
- [ ] PostgreSQL monitoring
- [ ] Hasura monitoring
- [ ] PostgreSQL sink monitoring
- [ ] Load balancer for Hasura requests
- [ ] Public endpoint for Hasura requests
- [ ] Rate limiting GraphQL requests
- [ ] Proper user and permission setup on PostgreSQL
